services:
  db:
    image: mysql:8.0
    container_name: dev-peaknode-db
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev-peaknode
      MYSQL_USER: dev-peaknode
      MYSQL_PASSWORD: dev-peaknode
    volumes:
      - ./db/data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:

  # redis:
  #   image: redis:7-alpine
  #   container_name: dev-workship-redis
  #   ports:
  #     - "63791:6379"
  #   volumes:
  #     - ./redis/data:/data


