services:
  db:
    image: mysql:8.0
    container_name: dev-peaknode-db
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev-peaknode
      MYSQL_USER: dev-peaknode
      MYSQL_PASSWORD: dev-peaknode
    volumes:
      - ./db/data:/var/lib/mysql
  minio-init:
    image: minio/mc:latest
    container_name: dev-storage
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc mb --ignore-existing local/pdf-local;
        mc anonymous set download local/pdf-local;
        echo 'MinIO bucket ready';
      "
    restart: on-failure

  # redis:
  #   image: redis:7-alpine
  #   container_name: dev-workship-redis
  #   ports:
  #     - "63791:6379"
  #   volumes:
  #     - ./redis/data:/data
